app: ui: AppBar: Do not remember the scroll state
 * After updating the dependencies, remembering the scroll state
   from the previous page ends up causing a crash with the
   following error:

	java.lang.IllegalStateException: Size(1080 x -80) is out of range.
	Each dimension must be between 0 and 16777215.